### ISSUE TITLE
Reuse Previous Waypoints

### ISSUE THREAD

**Issue by salaniz** [salaniz/CarND-DriveIT-System-Integration#3]
The waypoint updater currently first searches all waypoints for the closest one and then builds the list of next waypoints by looping through the number of needed following waypoints.
This could be done more efficently.

1. Remember the last closest waypoint and do a local search each time instead of calculating the distance to all waypoints. (Maybe check if the distance didn't change to drastically from last time. If it did, do a global search)
2. Check if it is possible to reuse the last list of "final_waypoints". Remove front waypoints which are now past the vehicle and add more at the end. Traffic light waypoints need to be updated!

**Comment by hdelgado** [comment]
You mean the same way we did on the previous project right?

**Comment by salaniz** [comment]
Which project do you exactly refer to, the path planning one?
Yes, it should be similar to that.

**Comment by salaniz** [comment]
So with the latest commit 58cc12a36db32450ed931a1ede064fb802e1b229, the closest waypoint search is a bit improved. Would it maybe be possible to start at the last index and then go left and right one step at a time until the distance increases for like X times in a row?

Also: can we do the same when we construct the next 100 "final_waypoints".  Currently, we construct them new every time, but maybe that's just easier like this.

**Comment by salaniz** [comment]
Since 4f0c02e584dae1032c359e67d3a08d19e1831b86 "final_waypoints" are also reused.
