### ISSUE TITLE
New Traffic Light Detection Pipeline

### ISSUE THREAD

**Issue by salaniz** [salaniz/CarND-DriveIT-System-Integration#4]
Implement the following pipeline (in hope that it will improve the TL detection)

1. Use Google Detection API to get a neural net that detects traffic lights and their position in the picture (no light color yet)
2. Extract the traffic light picture and train a classifier on traffic lights only to predict the color (red, yellow, green).

**Comment by salaniz** [comment]
Pretrained models for image detection can be found here: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

This could be used for step 1. There are even different models listed by their inference speed.

**Comment by shangliy** [comment]
The current pretrain the model structure is ssd-mobilenet.

**Comment by shangliy** [comment]
I have retrain the models for both sim and real images. The models are under the
 " CarND-DriveIT-System-Integration/tools/car_detector/models/ "

**Comment by salaniz** [comment]
Thanks, the new models seem to perform very good so I am closing this.
