### ISSUE TITLE
Improve PID hyperparameters

### ISSUE THREAD

**Issue by salaniz** [salaniz/CarND-DriveIT-System-Integration#7]
It seems that the current limitation of control is correct hyperparameters for steering (at high speeds) and for speed control (mainly breaking).

It would be good if everybody would test different combinations to find a good combination faster.

**Comment by hdelgado** [comment]
I can start checking in about 3 hrs

**Comment by salaniz** [comment]
This also includes the low pass filter hyperparameters.

**Comment by salaniz** [comment]
I have update the parameters according to Ruben's suggestion and it seems to improve the driving.
Further testing needed thuogh.

self.velocity_pid = PID(kp=1, ki=0, kd=0.1, mn=self.decel_limit, mx=self.accel_limit)
self.steer_pid = PID(kp=10, ki=0.1, kd=0.1, mn=-max_steer_angle, mx=max_steer_angle)
